version: '3.1'

services:
  app:
    build:  .
    container_name: book-rest-api-go
    ports:
      - "1337:1337"
    extra_hosts:
      - "host.docker.internal:172.21.0.2"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "4002:3306"
